language: csharp
mono: none
dotnet: 2.2

before_install:
  - cd src
install:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - dotnet nuget push triaxis.AspNetCore.ReverseProxy/bin/Release/*.nupkg -k $NUGET_API_KEY -s nuget.org
